import { Roboto } from "next/font/google"
import "./globals.css"

export const metadata = {
  title: 'NextProbando.js',
  description: 'Generated by Next.js',

}
export const vieport = {
  themeColor: 'black'
}

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  styles: ["italic", "normal"],
  subsets: ["latin"]
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        NAV
        <hr></hr>
        {children}
      </body>
    </html>
  )
}